### ISSUE TITLE
Problem with newer Excon versions and VCR

### ISSUE THREAD

**Issue by squarism** [hakanensari/jeff#2]
I thought I'd open this issue because Jeff requires Excon of specified versions.  I use a2z which uses Jeff and a nice use case is caching all requests that go to Amazon so I don't burn through my quota while doing testing.  VCR solves this problem nicely by watching for Excon requests and caches them to yaml.  Maybe you know about VCR already.  :smile:

I'm pretty sure this isn't your problem, so you can close this issue if it is off-topic of outside your boundary but I thought I'd mention it here anyway since Excon seems to be making some major changes lately? and maybe this might impact your gemspec.

When I used Excon 0.20.1 with a combination of jeff 0.5.0+ then I would get this

```
NoMethodError:
undefined method `connection' for #<Excon::Connection:0x007f9c45c4c488>
# (eval):3:in `get'
```

But when I roll back to jeff 0.4.3 + Excon 0.16.10, things work with no errors.  I am wrapping jeff and a2z in a VCR trying to cache the call to amazon.  So my stack looks something like this:

```
VCR caching block
   my code calls a2z
   a2z uses jeff for the amazon signature, and uses excon for transport
end
```

I don't believe a2z actually uses excon directly or any other http client.

Since my above explanation is pretty :poop:, I have reproduced the problem with as little code as possible below.

Here is the Gemfile I used.  Be sure to swap out 0.5.0 with the commented line 0.4.3.  Any Jeff gem newer than 0.4.3 (0.6.0 and 0.6.1) exhibit the problem.

```
# Gemfile
source "https://rubygems.org"

gem 'jeff', '= 0.5.0'
# gem 'jeff', '= 0.4.3'
gem 'vcr'
gem 'rspec'
```

Run the following after bundle with `bundle exec reproduce.rb` to use the flip-flopped jeff gem.

```
# reproduce.rb
# reproduce an issue with newer versions of jeff and vcr

require 'minitest/autorun'
require 'jeff'
require 'vcr'
require 'net/http'

VCR.configure do |c|
  c.cassette_library_dir = 'cassettes'
  c.hook_into :excon
end

class Foo
  include Jeff

  def initialize
    @endpoint = "http://localhost"
  end
end

describe Foo do
  def setup
    @subject = Foo.new
  end

  it 'does stuff' do
    VCR.use_cassette('synopsis') do
      @subject.connection
    end
  end
end
```

When this above reproduce.rb runs with 0.4.3 it works:

```
be ruby reproduce.rb
Run options: --seed 60054
# Running tests:
.
Finished tests in 0.001531s, 653.1679 tests/s, 0.0000 assertions/s.
```

When it fails:

```
1) Error:
test_0001_does_stuff(Foo):
NoMethodError: undefined method `connection' for #<Excon::Connection:0x007fb8c1479ba0>
  gems/vcr-2.4.0/lib/vcr/library_hooks/excon.rb:182:in `block in new'
  gems/vcr-2.4.0/lib/vcr/library_hooks/excon.rb:181:in `tap'
  gems/vcr-2.4.0/lib/vcr/library_hooks/excon.rb:181:in `new'
  gems/excon-0.20.1/lib/excon.rb:123:in `new'
  gems/ruby-1.9.3-p385@oss_contrib/gems/jeff-0.6.1/lib/jeff.rb:49:in `connection'
  reproduce.rb:28:in `block (3 levels) in <main>'
  gems/ruby-1.9.3-p385@oss_contrib/gems/vcr-2.4.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
  gems/ruby-1.9.3-p385@oss_contrib/gems/vcr-2.4.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
  gems/ruby-1.9.3-p385@oss_contrib/gems/vcr-2.4.0/lib/vcr.rb:173:in `use_cassette'
  reproduce.rb:27:in `block (2 levels) in <main>'
```

(i have snipped some things in the stacktrace above)

VCR even warns:

```
You are using Excon 0.20.1. VCR is known to work with Excon >= 0.9.6, < 0.17. It may not work with this version.
```

But the version of Excon is required by Jeff.  That's ok.  I rolled back to 0.4.3 and now I can cache Jeff signed amazon requests with VCR and all is happy.
